spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://106.14.93.187:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /static/

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx0b75f952d6504209
  mpAppSecret: 2059ac4389bbb610dae6ec70a096f011